main.py 11:53:58 <--------------Start logging--------------->
mysql_client.py 11:54:2 1049 (42000): Unknown database 'computer_servicse' 
Code: 1049
mysql_client.py 11:54:2 Database name is failed
mysql_client.py 11:56:6 Login...
['Cobalt', 'localhost:2525', 'Umsf_sqltutor', 'computer_service', 'Cobalt', 'localhost:2525', 'Umsf_sqltutor', 'computer_servicse']
mysql_client.py 11:56:9 Query: SELECT manager_id as "Індекс менеджера", manager_name as "Ім'я менеджера", manager_surname as "Прізвище менеджера" FROM manager order by manager_id ASC LIMIT 100;
mysql_client.py 11:56:14 Login...
['Cobalt', 'localhost:2525', 'Umsf_sqltutor', 'computer_service', 'Cobalt', 'localhost:2525', 'Umsf_sqltutor', 'computer_servicse']
mysql_client.py 11:56:18 Query: SELECT manager_id as "Індекс менеджера", manager_name as "Ім'я менеджера", manager_surname as "Прізвище менеджера" FROM manager order by manager_id ASC LIMIT 100;
mysql_client.py 11:56:30 Login...
['Cobalt', 'localhost:2525', 'Umsf_sqltutor', 'computer_service', 'Cobalt', 'localhost:2525', 'Umsf_sqltutor', 'computer_servicse']
main.py 11:57:13 Session is closed
